### PR TITLE
Improvement of some wordings (clearer and more consistent)

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
Check commits : 

Settings : Because "local" is not appropriate. The goal of the app is to generate download notification for files that are shared locally = shared with local users or groups (not external shares).

Provider : Because wordings had a lack of consistency width existing others.

### CODE REVIEW

**Review by jancborchardt — COMMENTED** [review]
To keep this a bit more concise, all of the "downloaded by" can do without "the":
- via desktop client
- via mobile app
- via browser

**Comment by nickvergessen** [comment]
This app is not being released anymore as per https://github.com/nextcloud/files_downloadactivity/issues/135

So changing the strings will also not have any effect, unless someone takes over ownership

**Comment by Jerome-Herbinet** [comment]
@nickvergessen one question anyway : Are you aware of any plans for Nextcloud to take over this app's features (which we think are interesting, although the wordings could be improved) and incorporate them directly into "Activity"? If not, how would you feel about promoting this idea within the development teams?

**Comment by nickvergessen** [comment]
> Are you aware of any plans for Nextcloud to take over this app's features (which we think are interesting, although the wordings could be improved) and incorporate them directly into "Activity"?

No

> If not, how would you feel about promoting this idea within the development teams?

I don't have the time nor energy for this and the general download counter of this app also doesn't sound like lot of people agree.

**Comment by Jerome-Herbinet** [comment]
> > Are you aware of any plans for Nextcloud to take over this app's features (which we think are interesting, although the wordings could be improved) and incorporate them directly into "Activity"?
> 
> No
> 
> > If not, how would you feel about promoting this idea within the development teams?
> 
> I don't have the time nor energy for this and the general download counter of this app also doesn't sound like lot of people agree.

OK thanks for the answer, it was just a question 🙂

**Pull request closed without merging**
