### PR TITLE
Ignore cases when the user is not logged in

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix nextcloud/server#3302

@EasyPeasy1 can you test this?

### CODE REVIEW

**Comment by EasyPeasy1** [comment]
@nickvergessen I downloaded multiple files and didn't receive any error. So I think it seems to work.
Great job! :-)

**Comment by pielonet** [comment]
Hi, It looks like I encounter the same Issue with NC 12.0.4

1. A regular LDAP user uploads and shares a file
2. An other LDAP user who received the share accesses its "Shared" folder and tries to download the file.
* If he clicks on "Download" in the files' context menu he gets an almost blank screen with the only error text :"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client."
* If he ticks one or several files and clicks the "Download" text, he gets an error screen with this message :"Backends provided no user object for <user_id_masked>
Storage is temporarily not available"

If trying to use the sync client, he gets a "server error" when trying to synchronize the "Shared" Folder (Same issue on Linux and MAC OS).

I could only solve the issue by manually copying the shared files to the destinee's private folder and launching occ files:scan. But this is a one time workaround...

Help needed please.

**Comment by nickvergessen** [comment]
If you face an issue, please create a new issue instead of commenting on a code change which was done over one year ago

**Comment by pielonet** [comment]
OK. Sorry. I thought I shouhd have... and have not !
I am doing it right away !

**Pull request merged**
